const image_path = "./images";
const icon_path = `./icons`;

export const images = {
  logo: `${image_path}/logo.svg`,
  burger_icon: `${image_path}/burger_icon.svg`,
  splash: `${image_path}/splash.jpg`,
  avatar: `${image_path}/avatar.png`,
  background_pattern: `${image_path}/background-pattern.png`,
  icons: {
    balance_inquiry: `${icon_path}/balance-inquiry.svg`,
    bank_credit: `${icon_path}/bank-credit.svg`,
    internet_package: `${icon_path}/internet-package.png`,
    recent_transactions: `${icon_path}/recent-transactions.svg`,
    telekish: `${icon_path}/telekish.svg`,
    topup: `${icon_path}/topup.png`,
    transfer: `${icon_path}/transfer.png`,
    bank_services: `${icon_path}/bank_services.png`,
    car_services: `${icon_path}/car_services.png`,
    mobile_services: `${icon_path}/mobile_services.png`,
    bills: `${icon_path}/bills.png`,
    non_customer_services: `${icon_path}/non_customer_services.png`,
    charity: `${icon_path}/charity.png`,
    team: `${icon_path}/team.svg`,
    profile: `${icon_path}/profile.svg`,
    shaparak: `${icon_path}/shaparak.png`,
    irankish: `${icon_path}/irankish.png`,
    payput_gray: `${icon_path}/payput_gray.png`,
    payput_red: `${icon_path}/payput_red.png`,
    man: `${icon_path}/man.svg`,
    man_white: `${icon_path}/man-white.svg`,
    woman: `${icon_path}/woman.svg`,
    woman_white: `${icon_path}/woman-white.svg`,
    water_bill: `${icon_path}/water-bill.png`,
    power_bill: `${icon_path}/power-bill.png`,
    gas_bill: `${icon_path}/gas-bill.png`,
    general_bill: `${icon_path}/general-bill.png`,
    toll: `${icon_path}/toll.png`,
    car_fine: `${icon_path}/car-fine.png`,
    car_restriction: `${icon_path}/car-restriction.png`,
  },
};
